name: generic_validator
description: A generic validator with business logic separation in mind.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  equatable: 2.0.3
  freezed_annotation: 1.1.0 

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  freezed: 1.1.1
  build_runner:

